name: Testing and Deploying
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unittests:
    name: Unittesting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        apt install pipx && pipx ensurepath
        python -m pip install --upgrade pip
        pipx install poetry
        poetry lock
        poetry install --all-extras
    - name: Run tests
      run: poetry run -- pytest ./tests
  publish-to-pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    needs: unittests
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        apt install pipx && pipx ensurepath
        python -m pip install --upgrade pip
        pipx install poetry
    - name: Build package
      run: |
        poetry lock
        poetry install
        poetry build --format wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1